CREATE TABLE IF NOT EXISTS app_user
(
    id    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name  VARCHAR(30)  NOT NULL COMMENT '姓名',
    pwd   VARCHAR(100) NOT NULL COMMENT '年龄',
    email VARCHAR(50)  NULL DEFAULT NULL UNIQUE COMMENT '邮箱',
    tel   VARCHAR(15)  NOT NULL COMMENT '手机号'
);
