
server:
  port: 9001
  servlet:
#    context-path: /server-demo
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: Blog
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: root
    password:
  sql:
    init:
      schema-locations: classpath:dev/h2/schema-h2.sql
      data-locations: classpath:dev/h2/data-h2.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true


springdoc:
  api-docs:
    version: openapi_3_0

#日志配置
logging:
  config:  classpath:dev/log4j2.xml
